### ISSUE TITLE
Update to Norm V3

### ISSUE THREAD

**Issue by ocywob** [42Paris/norminette#10]
Hello there,

Is his version comply with Norm v3? When I run norminette with -v flag it shows me this:

~/.norminettev3/norminette.rb -v
Local version:
1.0.0.rc1
Norminette version:
2.3.3

I don't have a change log but v3 can be found under here: https://cdn.intra.42.fr/pdf/pdf/20358/en.norm.pdf

I understand this code gets information from a remote server, so if the server is updated we should be good to go but I wanted to double check. 

Thanks!

**Comment by paulo-santana** [comment]
Nope. It's still validating the files with Norm v2.

**Comment by ocywob** [comment]
Can we somehow update it to v3? I like the rb version better than python version. It's easier to use in some cases.

**Comment by alexandregv** [comment]
Hi, it will not be updated officially and have little to no chance to get an update by the community since the ruby version is only a client which calls a server (hosted by 42), which is closed source. Please use the [new v3 python version](https://github.com/42School/norminette).
