### ISSUE TITLE
Fork, 42Network, Multiplications of Resources, Helsinki

### ISSUE THREAD

**Issue by nekosheen** [42Paris/norminette#2]
Hi,
I have some questions concerning the resources and the "strategy" of 42 Paris / 42 Network:
- Why did 42 Paris remove the attribution of the adaptation of the tool to Hive Helsinki ?
```
<div align="center">
  <sub>Adapted by <a href="https://hive.fi">Hive Helsinki</a> for all the 42 Network</sub>
</div>
```
- Why not fork the original repository ?

I mean we are going to have X copy of the norminette on Github with the exact same code, just with the institution changing (42paris/42sp/Hive...) I don't really understand.

**Comment by 42Paris** [comment]
Hello,

This tool is from Paris campus. Is the norminette tool. Our norminette is use in the all campus of the 42 network and hive just push him on github. Thats why hive wrote "Created by 42.fr". 

Next time I'll try not to forget about forks our tool.

Good evening to you,

Salty
