### ISSUE TITLE
:(

### ISSUE THREAD

**Issue by Surfingnet** [42Paris/norminette#4]
<img width="1280" alt="Capture d’écran 2020-05-28 à 07 28 00" src="https://user-images.githubusercontent.com/10564571/83102603-27793100-a0b5-11ea-90b8-e400ae067878.png">

**Comment by ghost** [comment]
did you solved the problem ?

**Comment by its-a-maxi** [comment]
I have the same problem
![Screenshot 2020-09-28 at 11 38 58](https://user-images.githubusercontent.com/71317877/94416776-8ba12400-017f-11eb-8a3b-4cdab430cc7a.png)

**Comment by its-a-maxi** [comment]
Ok, I have solved the issue, you just need to do a `bundle update` in the path where norminette is installed
