### ISSUE TITLE
Inconsistent use of whitespaces and tabulations in the code

### ISSUE THREAD

**Issue by adri326** [42Paris/norminette#5]
`norminette.rb` inconsistently uses whitespaces, tabulations and mixes of both to indent and align pieces of code:

![Screenshot_2020-08-02_23-28-53](https://user-images.githubusercontent.com/18118053/89132930-fe8f7500-d517-11ea-845b-f57d78575494.png)

Such inconsistent behavior is present throughout the source code:

- whitespace-only indentation (**18** lines, **9.6%** of the file, **13.2%** of the total indentation)
- tabulation-only indentation (**100** lines, **53.5%** of the file, **73.6%** of the total indentation)
- mixed indentation (**18** lines, **9.6%** of the file, **13.2%** of the total indentation)
- whitespace-only alignment (**3** lines, **1.6%** of the file, **15.7%** of the total alignment)
- tabulation-only alignment (**3** lines, **1.6%** of the file, **15.7%** of the total alignment)
- mixed alignment (**13** lines, **6.9%** of the file, **68.4%** of the total alignment)

This breaks both indentation and alignment between indentation/alignment "style regions".

I should also note that a lot of browsers use 8-wide tabulations by default, while your code seems to be based around 4-wide tabulations. Reading the code in my browser was hard enough that I had to clone the project.

**Please give a license to your code.**

**Comment by jgengo** [comment]
Hello,

This client has been written by 42 a long time ago. It's gonna be complicated for me to decide on a license.

But I will fix the tabulations/ident issues.
Thank you for your report.

**Comment by ghost** [comment]
Hello,

A new norminet version will come this year.
